<?xml version="1.0" ?>
<testsuite errors="38" failures="0" name="InequalityTest-20160316113118" tests="57" time="50.991">
	<testcase classname="InequalityTest" name="test_fpSSNTest_10" time="0.645"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_11" time="1.612"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_12" time="0.630"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_13" time="0.607"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_14" time="0.600"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_15" time="0.606"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_16" time="0.640"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_17" time="0.606"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_18" time="0.631"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_19" time="1.383"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_2" time="0.608"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_20" time="1.227"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_21" time="1.368"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_3" time="2.002"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_4" time="0.653"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_5" time="0.615"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_6" time="0.664"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_7" time="0.622"/>
	<testcase classname="InequalityTest" name="test_fpSSNTest_8" time="0.620"/>
	<testcase classname="InequalityTest" name="test_csSSNTest_1" time="0.632">
		<error message="'a so[52 chars]form 056-24-6544 application for a social secu[13 chars]ard ' != 'a so[52 chars]form #ss         application for a social secu[13 chars]ard '
- a social security number may be obtained by applying on form 056-24-6544 application for a social security number card 
?                                                              ^^^^^^^^^^^
+ a social security number may be obtained by applying on form #ss         application for a social security number card 
?                                                              ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 174, in test_csSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: 'a so[52 chars]form 056-24-6544 application for a social secu[13 chars]ard ' != 'a so[52 chars]form #ss         application for a social secu[13 chars]ard '
- a social security number may be obtained by applying on form 056-24-6544 application for a social security number card 
?                                                              ^^^^^^^^^^^
+ a social security number may be obtained by applying on form #ss         application for a social security number card 
?                                                              ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csSSNTest_2" time="0.653">
		<error message="'the [24 chars]ration does not reuse the 346-18-5642 social security numbers ' != 'the [24 chars]ration does not reuse the #ss         social security numbers '
- the social security administration does not reuse the 346-18-5642 social security numbers 
?                                                       ^^^^^^^^^^^
+ the social security administration does not reuse the #ss         social security numbers 
?                                                       ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 180, in test_csSSNTest_2
    self.assertEqual(Actuval, expected)
AssertionError: 'the [24 chars]ration does not reuse the 346-18-5642 social security numbers ' != 'the [24 chars]ration does not reuse the #ss         social security numbers '
- the social security administration does not reuse the 346-18-5642 social security numbers 
?                                                       ^^^^^^^^^^^
+ the social security administration does not reuse the #ss         social security numbers 
?                                                       ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csSSNTest_3" time="0.614">
		<error message="'it w[36 chars]ssn number 467-78-2884 that contained an invalid group number ' != 'it w[36 chars]ssn number #ss         that contained an invalid group number '
- it was possible to identify an unissued ssn number 467-78-2884 that contained an invalid group number 
?                                                    ^^^^^^^^^^^
+ it was possible to identify an unissued ssn number #ss         that contained an invalid group number 
?                                                    ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 186, in test_csSSNTest_3
    self.assertEqual(Actuval, expected)
AssertionError: 'it w[36 chars]ssn number 467-78-2884 that contained an invalid group number ' != 'it w[36 chars]ssn number #ss         that contained an invalid group number '
- it was possible to identify an unissued ssn number 467-78-2884 that contained an invalid group number 
?                                                    ^^^^^^^^^^^
+ it was possible to identify an unissued ssn number #ss         that contained an invalid group number 
?                                                    ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csSSNTest_4" time="0.616">
		<error message="'the [30 chars] security administration has allocated the number 300-55-6455 ' != 'the [30 chars] security administration has allocated the number #ss         '
- the highest area number the social security administration has allocated the number 300-55-6455 
?                                                                                     ^^^^^^^^^^^
+ the highest area number the social security administration has allocated the number #ss         
?                                                                                     ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 192, in test_csSSNTest_4
    self.assertEqual(Actuval, expected)
AssertionError: 'the [30 chars] security administration has allocated the number 300-55-6455 ' != 'the [30 chars] security administration has allocated the number #ss         '
- the highest area number the social security administration has allocated the number 300-55-6455 
?                                                                                     ^^^^^^^^^^^
+ the highest area number the social security administration has allocated the number #ss         
?                                                                                     ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csSSNTest_5" time="0.661">
		<error message="'the social security number is a nine-digit number in the format 123-12-1234 ' != 'the social security number is a nine-digit number in the format #ss         '
- the social security number is a nine-digit number in the format 123-12-1234 
?                                                                 ^^^^^^^^^^^
+ the social security number is a nine-digit number in the format #ss         
?                                                                 ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 198, in test_csSSNTest_5
    self.assertEqual(Actuval, expected)
AssertionError: 'the social security number is a nine-digit number in the format 123-12-1234 ' != 'the social security number is a nine-digit number in the format #ss         '
- the social security number is a nine-digit number in the format 123-12-1234 
?                                                                 ^^^^^^^^^^^
+ the social security number is a nine-digit number in the format #ss         
?                                                                 ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_1" time="0.670">
		<error message="' before #     people 198-22-1234 often 894-45-465[155 chars]oses' != ' before 1986  people #ss         often #ss       [155 chars]oses'
-  before #     people 198-22-1234 often 894-45-4654 did not obtain 656-96-1213 a social security number until the age of about 499-65-8798   since the numbers were used 465-88-4548 for income tracking purposes
+  before 1986  people #ss         often #ss         did not obtain #ss         a social security number until the age of about #ss           since the numbers were used #ss         for income tracking purposes
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 131, in test_fSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: ' before #     people 198-22-1234 often 894-45-465[155 chars]oses' != ' before 1986  people #ss         often #ss       [155 chars]oses'
-  before #     people 198-22-1234 often 894-45-4654 did not obtain 656-96-1213 a social security number until the age of about 499-65-8798   since the numbers were used 465-88-4548 for income tracking purposes
+  before 1986  people #ss         often #ss         did not obtain #ss         a social security number until the age of about #ss           since the numbers were used #ss         for income tracking purposes

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_2" time="0.706">
		<error message="'a he[14 chars]ther 787-84-2565 symbol can be added 787-87-84[401 chars]ulf.' != 'a he[14 chars]ther #ss         symbol can be added #ss      [401 chars]ulf.'
Diff is 945 characters long. Set self.maxDiff to None to see it." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 137, in test_fSSNTest_2
    self.assertEqual(Actuval, expected)
AssertionError: 'a he[14 chars]ther 787-84-2565 symbol can be added 787-87-84[401 chars]ulf.' != 'a he[14 chars]ther #ss         symbol can be added #ss      [401 chars]ulf.'
Diff is 945 characters long. Set self.maxDiff to None to see it.
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_3" time="1.240">
		<error message="'the area number 233-49-7836 represented the office code w[20 chars]sued' != 'the area number #ss         represented the office code w[20 chars]sued'
- the area number 233-49-7836 represented the office code where the card was issued
?                 ^^^^^^^^^^^
+ the area number #ss         represented the office code where the card was issued
?                 ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 143, in test_fSSNTest_3
    self.assertEqual(Actuval, expected)
AssertionError: 'the area number 233-49-7836 represented the office code w[20 chars]sued' != 'the area number #ss         represented the office code w[20 chars]sued'
- the area number 233-49-7836 represented the office code where the card was issued
?                 ^^^^^^^^^^^
+ the area number #ss         represented the office code where the card was issued
?                 ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_4" time="0.668">
		<error message="'numb[24 chars]ing in the northeast 230-67-3666 and moving south and westward' != 'numb[24 chars]ing in the northeast #ss         and moving south and westward'
- numbers were assigned beginning in the northeast 230-67-3666 and moving south and westward
?                                                  ^^^^^^^^^^^
+ numbers were assigned beginning in the northeast #ss         and moving south and westward
?                                                  ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 149, in test_fSSNTest_4
    self.assertEqual(Actuval, expected)
AssertionError: 'numb[24 chars]ing in the northeast 230-67-3666 and moving south and westward' != 'numb[24 chars]ing in the northeast #ss         and moving south and westward'
- numbers were assigned beginning in the northeast 230-67-3666 and moving south and westward
?                                                  ^^^^^^^^^^^
+ numbers were assigned beginning in the northeast #ss         and moving south and westward
?                                                  ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_5" time="0.621">
		<error message="'they[37 chars]nce of digits from 564-22-0001 to 263-75-9999 within the group' != 'they[37 chars]nce of digits from #ss         to #ss         within the group'
- they represent a straight numerical sequence of digits from 564-22-0001 to 263-75-9999 within the group
?                                                             ^^^^^^^^^^^    ^^^^^^^^^^^
+ they represent a straight numerical sequence of digits from #ss         to #ss         within the group
?                                                             ^^^^^^^^^^^    ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 155, in test_fSSNTest_5
    self.assertEqual(Actuval, expected)
AssertionError: 'they[37 chars]nce of digits from 564-22-0001 to 263-75-9999 within the group' != 'they[37 chars]nce of digits from #ss         to #ss         within the group'
- they represent a straight numerical sequence of digits from 564-22-0001 to 263-75-9999 within the group
?                                                             ^^^^^^^^^^^    ^^^^^^^^^^^
+ they represent a straight numerical sequence of digits from #ss         to #ss         within the group
?                                                             ^^^^^^^^^^^    ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_6" time="0.649">
		<error message="&quot;dist[18 chars]mber 400-10-2993 in advertisements for his com[20 chars]tity&quot; != &quot;dist[18 chars]mber #ss         in advertisements for his com[20 chars]tity&quot;
- distributed his ssn number 400-10-2993 in advertisements for his company's lifelock identity
?                            ^^^^^^^^^^^
+ distributed his ssn number #ss         in advertisements for his company's lifelock identity
?                            ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 161, in test_fSSNTest_6
    self.assertEqual(Actuval, expected)
AssertionError: "dist[18 chars]mber 400-10-2993 in advertisements for his com[20 chars]tity" != "dist[18 chars]mber #ss         in advertisements for his com[20 chars]tity"
- distributed his ssn number 400-10-2993 in advertisements for his company's lifelock identity
?                            ^^^^^^^^^^^
+ distributed his ssn number #ss         in advertisements for his company's lifelock identity
?                            ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fSSNTest_7" time="0.612">
		<error message="'since group numbers 564-77-3732 were allocated in a regular pattern' != 'since group numbers #ss         were allocated in a regular pattern'
- since group numbers 564-77-3732 were allocated in a regular pattern
?                     ^^^^^^^^^^^
+ since group numbers #ss         were allocated in a regular pattern
?                     ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 167, in test_fSSNTest_7
    self.assertEqual(Actuval, expected)
AssertionError: 'since group numbers 564-77-3732 were allocated in a regular pattern' != 'since group numbers #ss         were allocated in a regular pattern'
- since group numbers 564-77-3732 were allocated in a regular pattern
?                     ^^^^^^^^^^^
+ since group numbers #ss         were allocated in a regular pattern
?                     ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fpSSNTest_1" time="0.630">
		<error message="' #   ' != ' 1234'
-  #   
+  1234
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 261, in test_fpSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: ' #   ' != ' 1234'
-  #   
+  1234

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fpSSNTest_9" time="0.592">
		<error message="' #            ' != ' 1232134124434'
-  #            
+  1232134124434
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 309, in test_fpSSNTest_9
    self.assertEqual(Actuval, expected)
AssertionError: ' #            ' != ' 1232134124434'
-  #            
+  1232134124434

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_1" time="0.609">
		<error message="' 146-12-4123 ' != ' #ss         '
-  146-12-4123 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 28, in test_iSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: ' 146-12-4123 ' != ' #ss         '
-  146-12-4123 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_10" time="0.593">
		<error message="' 524-57-7512 ' != ' #ss         '
-  524-57-7512 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 82, in test_iSSNTest_10
    self.assertEqual(Actuval, expected)
AssertionError: ' 524-57-7512 ' != ' #ss         '
-  524-57-7512 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_11" time="1.264">
		<error message="' 688-84-8988 ' != ' #ss         '
-  688-84-8988 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 88, in test_iSSNTest_11
    self.assertEqual(Actuval, expected)
AssertionError: ' 688-84-8988 ' != ' #ss         '
-  688-84-8988 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_12" time="1.267">
		<error message="' 871-16-5328 ' != ' #ss         '
-  871-16-5328 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 94, in test_iSSNTest_12
    self.assertEqual(Actuval, expected)
AssertionError: ' 871-16-5328 ' != ' #ss         '
-  871-16-5328 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_13" time="0.694">
		<error message="'123-12-1233' != '#ss        '
- 123-12-1233
+ #ss        
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 100, in test_iSSNTest_13
    self.assertEqual(Actuval, expected)
AssertionError: '123-12-1233' != '#ss        '
- 123-12-1233
+ #ss        

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_14" time="1.330">
		<error message="'642-37-6739' != '#ss        '
- 642-37-6739
+ #ss        
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 106, in test_iSSNTest_14
    self.assertEqual(Actuval, expected)
AssertionError: '642-37-6739' != '#ss        '
- 642-37-6739
+ #ss        

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_15" time="3.644">
		<error message="'702-78-2038' != '#ss        '
- 702-78-2038
+ #ss        
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 112, in test_iSSNTest_15
    self.assertEqual(Actuval, expected)
AssertionError: '702-78-2038' != '#ss        '
- 702-78-2038
+ #ss        

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_16" time="0.631">
		<error message="'548-17-7489' != '#ss        '
- 548-17-7489
+ #ss        
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 118, in test_iSSNTest_16
    self.assertEqual(Actuval, expected)
AssertionError: '548-17-7489' != '#ss        '
- 548-17-7489
+ #ss        

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_17" time="1.831">
		<error message="'473-78-8473' != '#ss        '
- 473-78-8473
+ #ss        
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 124, in test_iSSNTest_17
    self.assertEqual(Actuval, expected)
AssertionError: '473-78-8473' != '#ss        '
- 473-78-8473
+ #ss        

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_2" time="0.636">
		<error message="' 679-34-4567 ' != ' #ss         '
-  679-34-4567 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 34, in test_iSSNTest_2
    self.assertEqual(Actuval, expected)
AssertionError: ' 679-34-4567 ' != ' #ss         '
-  679-34-4567 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_3" time="2.260">
		<error message="' 801-54-4852 ' != ' #ss         '
-  801-54-4852 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 40, in test_iSSNTest_3
    self.assertEqual(Actuval, expected)
AssertionError: ' 801-54-4852 ' != ' #ss         '
-  801-54-4852 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_4" time="0.599">
		<error message="' 787-87-6878 ' != ' #ss         '
-  787-87-6878 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 46, in test_iSSNTest_4
    self.assertEqual(Actuval, expected)
AssertionError: ' 787-87-6878 ' != ' #ss         '
-  787-87-6878 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_5" time="1.816">
		<error message="' 522-86-8468 ' != ' #ss         '
-  522-86-8468 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 52, in test_iSSNTest_5
    self.assertEqual(Actuval, expected)
AssertionError: ' 522-86-8468 ' != ' #ss         '
-  522-86-8468 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_6" time="1.637">
		<error message="' 887-86-6857 ' != ' #ss         '
-  887-86-6857 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 58, in test_iSSNTest_6
    self.assertEqual(Actuval, expected)
AssertionError: ' 887-86-6857 ' != ' #ss         '
-  887-86-6857 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_7" time="0.610">
		<error message="' 789-89-8877 ' != ' #ss         '
-  789-89-8877 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 64, in test_iSSNTest_7
    self.assertEqual(Actuval, expected)
AssertionError: ' 789-89-8877 ' != ' #ss         '
-  789-89-8877 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_8" time="0.645">
		<error message="' 878-85-5557 ' != ' #ss         '
-  878-85-5557 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 70, in test_iSSNTest_8
    self.assertEqual(Actuval, expected)
AssertionError: ' 878-85-5557 ' != ' #ss         '
-  878-85-5557 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iSSNTest_9" time="0.616">
		<error message="' 787-84-2565 ' != ' #ss         '
-  787-84-2565 
+  #ss         
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 76, in test_iSSNTest_9
    self.assertEqual(Actuval, expected)
AssertionError: ' 787-84-2565 ' != ' #ss         '
-  787-84-2565 
+  #ss         

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcSSNTest_1" time="0.658">
		<error message="'these card number  234-27-8843  are issued to people who hav[38 chars]u.s.' != 'these card number  #ss          are issued to people who hav[38 chars]u.s.'
- these card number  234-27-8843  are issued to people who have temporary work authorization in the u.s.
?                    ^^^^^^^^^^^
+ these card number  #ss          are issued to people who have temporary work authorization in the u.s.
?                    ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 224, in test_mcSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: 'these card number  234-27-8843  are issued to people who hav[38 chars]u.s.' != 'these card number  #ss          are issued to people who hav[38 chars]u.s.'
- these card number  234-27-8843  are issued to people who have temporary work authorization in the u.s.
?                    ^^^^^^^^^^^
+ these card number  #ss          are issued to people who have temporary work authorization in the u.s.
?                    ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcSSNTest_2" time="0.621">
		<error message="'it h[35 chars]tifier  345-70-3300  for individuals within the united states ' != 'it h[35 chars]tifier  #ss          for individuals within the united states '
- it has since come to be used as an identifier  345-70-3300  for individuals within the united states 
?                                                ^^^^^^^^^^^
+ it has since come to be used as an identifier  #ss          for individuals within the united states 
?                                                ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 230, in test_mcSSNTest_2
    self.assertEqual(Actuval, expected)
AssertionError: 'it h[35 chars]tifier  345-70-3300  for individuals within the united states ' != 'it h[35 chars]tifier  #ss          for individuals within the united states '
- it has since come to be used as an identifier  345-70-3300  for individuals within the united states 
?                                                ^^^^^^^^^^^
+ it has since come to be used as an identifier  #ss          for individuals within the united states 
?                                                ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcSSNTest_3" time="0.613">
		<error message="'the [23 chars]three digits  554-44-6774  is assigned by geographical region ' != 'the [23 chars]three digits  #ss          is assigned by geographical region '
- the area number  the first three digits  554-44-6774  is assigned by geographical region 
?                                          ^^^^^^^^^^^
+ the area number  the first three digits  #ss          is assigned by geographical region 
?                                          ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 236, in test_mcSSNTest_3
    self.assertEqual(Actuval, expected)
AssertionError: 'the [23 chars]three digits  554-44-6774  is assigned by geographical region ' != 'the [23 chars]three digits  #ss          is assigned by geographical region '
- the area number  the first three digits  554-44-6774  is assigned by geographical region 
?                                          ^^^^^^^^^^^
+ the area number  the first three digits  #ss          is assigned by geographical region 
?                                          ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_nlSSNTest_1" time="0.621">
		<error message="'the [26 chars]mber 223-49-7858  issued to an individual for [16 chars]ion ' != 'the [26 chars]mber #ss          issued to an individual for [16 chars]ion '
- the social security account number 223-49-7858  issued to an individual for purposes of section 
?                                    ^^^^^^^^^^^
+ the social security account number #ss          issued to an individual for purposes of section 
?                                    ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 388, in test_nlSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: 'the [26 chars]mber 223-49-7858  issued to an individual for [16 chars]ion ' != 'the [26 chars]mber #ss          issued to an individual for [16 chars]ion '
- the social security account number 223-49-7858  issued to an individual for purposes of section 
?                                    ^^^^^^^^^^^
+ the social security account number #ss          issued to an individual for purposes of section 
?                                    ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pSSNTest_1" time="0.621">
		<error message="'many[65 chars]e and processing of social security numbers like  102-12-2832 ' != 'many[65 chars]e and processing of social security numbers like  #ss         '
- many citizens and privacy advocates are concerned about the disclosure and processing of social security numbers like  102-12-2832 
?                                                                                                                        ^^^^^^^^^^^
+ many citizens and privacy advocates are concerned about the disclosure and processing of social security numbers like  #ss         
?                                                                                                                        ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 205, in test_pSSNTest_1
    self.assertEqual(Actuval, expected)
AssertionError: 'many[65 chars]e and processing of social security numbers like  102-12-2832 ' != 'many[65 chars]e and processing of social security numbers like  #ss         '
- many citizens and privacy advocates are concerned about the disclosure and processing of social security numbers like  102-12-2832 
?                                                                                                                        ^^^^^^^^^^^
+ many citizens and privacy advocates are concerned about the disclosure and processing of social security numbers like  #ss         
?                                                                                                                        ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pSSNTest_2" time="0.645">
		<error message="&quot;the most common type contains the cardholder's name and number 223-88-3734&quot; != &quot;the most common type contains the cardholder's name and number #ss         &quot;
- the most common type contains the cardholder's name and number 223-88-3734
?                                                                ^^^^^^^^^^^
+ the most common type contains the cardholder's name and number #ss         
?                                                                ^^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 211, in test_pSSNTest_2
    self.assertEqual(Actuval, expected)
AssertionError: "the most common type contains the cardholder's name and number 223-88-3734" != "the most common type contains the cardholder's name and number #ss         "
- the most common type contains the cardholder's name and number 223-88-3734
?                                                                ^^^^^^^^^^^
+ the most common type contains the cardholder's name and number #ss         
?                                                                ^^^^^^^^^^^^

]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pSSNTest_3" time="0.624">
		<error message="'it i[35 chars]urity number 345-23-3737  at the time of birth in the hospital' != 'it i[35 chars]urity number #ss          at the time of birth in the hospital'
- it is best to apply for baby social security number 345-23-3737  at the time of birth in the hospital
?                                                     ^^^^^^^^^^^
+ it is best to apply for baby social security number #ss          at the time of birth in the hospital
?                                                     ^^^^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 217, in test_pSSNTest_3
    self.assertEqual(Actuval, expected)
AssertionError: 'it i[35 chars]urity number 345-23-3737  at the time of birth in the hospital' != 'it i[35 chars]urity number #ss          at the time of birth in the hospital'
- it is best to apply for baby social security number 345-23-3737  at the time of birth in the hospital
?                                                     ^^^^^^^^^^^
+ it is best to apply for baby social security number #ss          at the time of birth in the hospital
?                                                     ^^^^^^^^^^^

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
