<?xml version="1.0" ?>
<testsuite errors="54" failures="0" name="InequalityTest-20160318121605" tests="54" time="52.122">
	<testcase classname="InequalityTest" name="test_csAcronymTest_1" time="9.840">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 257, in test_csAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csAcronymTest_2" time="0.845">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 263, in test_csAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csAcronymTest_3" time="0.804">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 269, in test_csAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csAcronymTest_4" time="0.806">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 275, in test_csAcronymTest_4
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csAcronymTest_5" time="0.906">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 281, in test_csAcronymTest_5
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_csAcronymTest_6" time="0.586">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 287, in test_csAcronymTest_6
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_1" time="0.898">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 214, in test_fAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_2" time="0.596">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 220, in test_fAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_3" time="1.819">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 226, in test_fAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_4" time="0.694">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 232, in test_fAcronymTest_4
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_5" time="2.121">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 238, in test_fAcronymTest_5
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_6" time="0.684">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 244, in test_fAcronymTest_6
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fAcronymTest_7" time="0.681">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 250, in test_fAcronymTest_7
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fpAcronymTest_1" time="0.718">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 332, in test_fpAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fpAcronymTest_2" time="0.600">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 338, in test_fpAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_fpAcronymTest_3" time="0.694">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 344, in test_fpAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_1" time="0.612">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 27, in test_iAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_10" time="0.680">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 69, in test_iAcronymTest_10
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_11" time="0.655">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 75, in test_iAcronymTest_11
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_12" time="0.691">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 81, in test_iAcronymTest_12
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_13" time="0.627">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 87, in test_iAcronymTest_13
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_14" time="0.606">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 93, in test_iAcronymTest_14
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_15" time="0.648">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 99, in test_iAcronymTest_15
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_16" time="0.659">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 105, in test_iAcronymTest_16
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_17" time="0.680">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 111, in test_iAcronymTest_17
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_18" time="0.636">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 117, in test_iAcronymTest_18
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_19" time="0.680">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 123, in test_iAcronymTest_19
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_2" time="0.640">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 33, in test_iAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_20" time="0.636">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 129, in test_iAcronymTest_20
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_21" time="0.635">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 135, in test_iAcronymTest_21
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_22" time="1.408">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 141, in test_iAcronymTest_22
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_23" time="1.575">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 147, in test_iAcronymTest_23
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_24" time="0.709">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 153, in test_iAcronymTest_24
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_25" time="1.612">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 159, in test_iAcronymTest_25
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_26" time="0.613">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 165, in test_iAcronymTest_26
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_27" time="1.809">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 171, in test_iAcronymTest_27
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_28" time="0.647">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 177, in test_iAcronymTest_28
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_29" time="0.673">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 183, in test_iAcronymTest_29
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_3" time="0.609">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 39, in test_iAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_30" time="0.641">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 189, in test_iAcronymTest_30
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_31" time="0.633">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 195, in test_iAcronymTest_31
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_32" time="0.632">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 201, in test_iAcronymTest_32
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_33" time="0.638">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 207, in test_iAcronymTest_33
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_5" time="0.611">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 45, in test_iAcronymTest_5
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_7" time="0.609">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 51, in test_iAcronymTest_7
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_8" time="0.606">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 57, in test_iAcronymTest_8
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_iAcronymTest_9" time="0.604">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 63, in test_iAcronymTest_9
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcAcronymTest_1" time="0.634">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 313, in test_mcAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcAcronymTest_2" time="1.325">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 319, in test_mcAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_mcAcronymTest_3" time="0.652">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 325, in test_mcAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_nlAcronymTest_1" time="0.617">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 351, in test_nlAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pAcronymTest_1" time="0.628">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 294, in test_pAcronymTest_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pAcronymTest_2" time="0.633">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 300, in test_pAcronymTest_2
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="InequalityTest" name="test_pAcronymTest_3" time="0.625">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 306, in test_pAcronymTest_3
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 16, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
